"""empty message

Revision ID: 0d8dc24f9ddd
Revises: 50d459c23fac
Create Date: 2019-07-23 14:45:28.048728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8dc24f9ddd'
down_revision = '50d459c23fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('is_likes_post_id_fkey', 'is_likes', type_='foreignkey')
    op.create_foreign_key(None, 'is_likes', 'recipes', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'is_likes', type_='foreignkey')
    op.create_foreign_key('is_likes_post_id_fkey', 'is_likes', 'users', ['post_id'], ['id'])
    # ### end Alembic commands ###
