"""empty message

Revision ID: 0ffba6b4e0ce
Revises: d3b1ffe2d9d4
Create Date: 2019-07-28 23:09:50.461935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffba6b4e0ce'
down_revision = 'd3b1ffe2d9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'date_posted')
    # ### end Alembic commands ###
