"""empty message

Revision ID: 12e51e0ebfbd
Revises: 7918be0af89c
Create Date: 2019-07-19 23:18:51.979271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e51e0ebfbd'
down_revision = '7918be0af89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'instructions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('instructions', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
