"""empty message

Revision ID: 34dbd9f3e55f
Revises: 0ffba6b4e0ce
Create Date: 2019-07-29 16:26:17.302962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34dbd9f3e55f'
down_revision = '0ffba6b4e0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('imgUrl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'imgUrl')
    # ### end Alembic commands ###
