"""empty message

Revision ID: 54f04443a754
Revises: 7cf92792e156
Create Date: 2019-07-26 14:29:36.743572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f04443a754'
down_revision = '7cf92792e156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe', sa.Column('is_subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribe', 'is_subscribed')
    # ### end Alembic commands ###
