"""empty message

Revision ID: 5e51ed1d29d2
Revises: 
Create Date: 2019-07-14 15:06:32.884057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e51ed1d29d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('provider_pic', sa.String(length=500), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
