"""empty message

Revision ID: 703826e56cd8
Revises: a11b2b9f869b
Create Date: 2019-07-19 22:42:34.613421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703826e56cd8'
down_revision = 'a11b2b9f869b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('ingredients_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'ingredients_id')
    # ### end Alembic commands ###
