"""empty message

Revision ID: 7cf92792e156
Revises: adc3dc16e550
Create Date: 2019-07-26 10:57:05.646397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf92792e156'
down_revision = 'adc3dc16e550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_subscribing', sa.Integer(), nullable=False),
    sa.Column('user_subscribed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_subscribed'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_subscribing'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_subscribing', 'user_subscribed')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribe')
    # ### end Alembic commands ###
