"""empty message

Revision ID: adc3dc16e550
Revises: 0d8dc24f9ddd
Create Date: 2019-07-24 17:21:53.605664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc3dc16e550'
down_revision = '0d8dc24f9ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'description',
               existing_type=sa.String(length=2200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
