"""empty message

Revision ID: d9effbad3dd5
Revises: 703826e56cd8
Create Date: 2019-07-19 23:07:35.184522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9effbad3dd5'
down_revision = '703826e56cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('ingredient_id', sa.Integer(), nullable=True))
    op.drop_column('ingredients', 'ingredients_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('ingredients_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ingredients', 'ingredient_id')
    # ### end Alembic commands ###
