"""empty message

Revision ID: eed336c83397
Revises: 5e51ed1d29d2
Create Date: 2019-07-14 15:07:12.841734

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'eed336c83397'
down_revision = '5e51ed1d29d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OAuth',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('provider', sa.String(
                        length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('token', sqlalchemy_utils.types.json.JSONType(),
                              nullable=False),
                    sa.Column('provider_user_id', sa.String(
                        length=256), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('provider_user_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OAuth')
    # ### end Alembic commands ###
